@{
    RootModule = 'PowerShellFileManager.psm1'
    ModuleVersion = '2.1.0'
    GUID = '5e482a95-6f2f-4928-8c75-b25baf8f93f6'
    Author = 'Heathen-Volholl'
    CompanyName = 'Community'
    Copyright = '(c) 2025 Heathen-Volholl. All rights reserved. MIT License.'
    Description = 'Advanced PowerShell 7 File Manager with command-centric design, rich metadata display, and extensive PowerShell integration'
    PowerShellVersion = '7.0'
    CompatiblePSEditions = @('Core')

    # Functions to export - the complete public API. Kept in sync with the
    # Export-ModuleMember calls in src/Modules/*.psm1 (verified by tests).
    FunctionsToExport = @(
        'Add-CommandToHistory'
        'Add-HostsEntry'
        'Add-NavigationHistory'
        'Backup-HostsFile'
        'Build-FileQuery'
        'Clear-CompletedEnhancedOperations'
        'Clear-FileCache'
        'Clear-PerformanceMetrics'
        'Clear-RecycleBinItems'
        'Clear-SearchHistory'
        'Connect-FTP'
        'Connect-SFTP'
        'Convert-ColorFormat'
        'Convert-PathFormat'
        'Disable-AwakeMode'
        'Edit-FileMetadata'
        'Enable-AwakeMode'
        'Enable-IntegrityMonitoring'
        'Expand-ArchiveFile'
        'Export-DiagnosticData'
        'Export-PerformanceReport'
        'Find-DuplicateFiles'
        'Find-Shortcut'
        'Get-AccentedCharacter'
        'Get-ArchiveContent'
        'Get-AwakeStatus'
        'Get-BackgroundOperations'
        'Get-BatchOperationTemplate'
        'Get-CloudSyncStatus'
        'Get-ColorFromScreen'
        'Get-CommandHistory'
        'Get-DiskSpace'
        'Get-EnhancedOperationStatus'
        'Get-ExternalTool'
        'Get-FileACL'
        'Get-FileChecksum'
        'Get-FileIndexStatistics'
        'Get-FileLock'
        'Get-FileManagerConfig'
        'Get-FileManagerHealth'
        'Get-FileManagerLogs'
        'Get-FileManagerMetrics'
        'Get-FileMetadata'
        'Get-FileTemplate'
        'Get-FolderSize'
        'Get-FuzzyMatch'
        'Get-GitStatus'
        'Get-HostsEntry'
        'Get-ImageInfo'
        'Get-KeyboardShortcut'
        'Get-NavigationHistory'
        'Get-ObjectDetails'
        'Get-OperationStatistics'
        'Get-PluginList'
        'Get-RecycleBinItems'
        'Get-ReparsePointTarget'
        'Get-SavedSearches'
        'Get-SearchHistory'
        'Get-SearchSuggestions'
        'Get-SpecialSymbol'
        'Get-TextFromImage'
        'Get-WindowTopMostStatus'
        'Get-WorkspaceLayout'
        'Initialize-FileManagerLogging'
        'Initialize-RunspacePool'
        'Install-Plugin'
        'Invoke-CommandPalette'
        'Invoke-ExternalTool'
        'Invoke-FileComparison'
        'Invoke-GitDiff'
        'Invoke-NavigationBack'
        'Invoke-NavigationForward'
        'Invoke-PowerRename'
        'Invoke-QuickFilter'
        'Invoke-WithAwakeMode'
        'Move-LogFileToBackup'
        'New-Archive'
        'New-BatchOperationTemplate'
        'New-DirectoryEntry'
        'New-FileFromTemplate'
        'New-OperationRecord'
        'New-QueryBuilder'
        'New-RenamePattern'
        'New-ScriptWorkspace'
        'New-Symlink'
        'Optimize-FileCache'
        'Protect-FileWithPassword'
        'Register-ExternalTool'
        'Remove-FileSecurely'
        'Remove-HostsEntry'
        'Remove-ItemToRecycleBin'
        'Remove-OldLogFiles'
        'Remove-SecureFile'
        'Rename-FileBatch'
        'Reset-FileManagerConfig'
        'Resize-Image'
        'Resolve-NormalizedPath'
        'Restore-RecycleBinItem'
        'Save-SearchQuery'
        'Save-WorkspaceSnapshot'
        'Search-Content'
        'Search-Files'
        'Search-FilesFuzzy'
        'Search-IndexedFiles'
        'Set-FileACL'
        'Set-FileDigitalSignature'
        'Set-FileManagerConfig'
        'Set-WindowAlwaysOnTop'
        'Set-WindowLayout'
        'Show-AudioPreview'
        'Show-EnhancedPreview'
        'Show-ExcelPreview'
        'Show-FileLockInfo'
        'Show-FilePreview'
        'Show-GCodePreview'
        'Show-MarkdownPreview'
        'Show-ObjectInspector'
        'Show-PDFPreview'
        'Show-PerformanceSummary'
        'Show-QuickAccentMenu'
        'Show-ShortcutGuide'
        'Show-STLPreview'
        'Show-SVGPreview'
        'Show-TemplateMenu'
        'Show-VideoPreview'
        'Show-WindowPinIndicator'
        'Show-WordDocumentPreview'
        'Show-WorkspaceLayoutMenu'
        'Start-BackgroundCopy'
        'Start-BatchOperation'
        'Start-ConditionalBatchOperation'
        'Start-EnhancedBackgroundCopy'
        'Start-FileManager'
        'Start-PerformanceTracking'
        'Start-RunspaceManager'
        'Start-ScreenTextExtractor'
        'Stop-BackgroundOperation'
        'Stop-EnhancedOperation'
        'Stop-PerformanceTracking'
        'Switch-WindowAlwaysOnTop'
        'Sync-Directories'
        'Test-FileDigitalSignature'
        'Test-FileIntegrity'
        'Test-FileLocked'
        'Test-PathTraversal'
        'Test-PowerToysIntegrations'
        'Test-ReparsePoint'
        'Test-SafePath'
        'Test-StartupHealth'
        'Uninstall-Plugin'
        'Unlock-File'
        'Unprotect-FileWithPassword'
        'Unregister-ExternalTool'
        'Update-ExternalTool'
        'Update-FileIndex'
        'Write-FileManagerLog'
        'Write-Log'
    )

    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @()

    PrivateData = @{
        PSData = @{
            Tags = @('FileManager', 'PowerShell', 'GUI', 'FileOperations', 'Metadata', 'Search')
            LicenseUri = 'https://github.com/J-Ellette/PowerShellFileManager/blob/main/LICENSE'
            ProjectUri = 'https://github.com/J-Ellette/PowerShellFileManager'
            RequireLicenseAcceptance = $false
        }
    }
}
