name: PowerShield Scan

on:
  push:
    paths:
      - '**/*.ps1'
      - '**/*.psm1'
      - '**/*.psd1'
  pull_request:
    paths:
      - '**/*.ps1'
      - '**/*.psm1'
      - '**/*.psd1'
  workflow_dispatch:

jobs:
  scan:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: PowerShield: PowerShell Security Scanner
        uses: J-Ellette/PowerShield@PowerShell_Security_Scanning
        # with:
        #   <input-name>: <value>
